### ISSUE TITLE
Update README.md to match Backdrop example

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/service_links#1]
The readme for a contrib project should to contain both a section about `License` as well as `Maintainer Information` (as per the backdrop contrib maintainer agreement).  Additionally, I like the heading for `Credits` to give proper emphasis to the section for those who've worked on the project. :)
 
There's an example README  that I *usually* copy/paste it when porting a module -- though, sometimes, I forget ;). It's located here: https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md.  It already contains the markdown formatting, as well as all the sections needed for Backdrop projects.

**Comment by jackaponte** [comment]
Thanks for the suggestions, Jen! I'll try to get to this when I return for my next round of work on the project.

**Comment by jackaponte** [comment]
Closing this issue since this project is now inactive, see #2.
