### ISSUE TITLE
Abandoning this incomplete module port

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/service_links#2]
The [Ridiculously Responsive Social Share Buttons module](https://backdropcms.org/project/rrssb) ported from Drupal 7 meets our clients' needs, so we're no longer working on this port of Service Links to Backdrop.

I'm making note of this here so people know this project's status, but I'll also see if there are other steps I should take here to more officially make this project dormant.

@jenlampton I believe you were the only person who ever expressed interest in this project; let me know if you'd like me to leave it open here in GitHub or if you'd like to do something with the work done to date!

**Comment by jenlampton** [comment]
I think leaving it here is a good plan, in case someone else wants to work with it in the future. I'm not using it at the moment either :)

**Comment by jackaponte** [comment]
Thanks for the feedback @jenlampton! After reading [the user guide page on maintaining projects](https://backdropcms.org/user-guide/maintaining-your-project) I'm going to make a note about the project no longer being active, but I won't archive it in case someone wants to create an issue here and pick things up again.

**Comment by jackaponte** [comment]
Closing this conversation now.
